#ifndef __TYPES_H__
#define __TYPES_H__

namespace ntt {

    enum class CodeGeneratorType {
        INTEGER_TERM, STRING_TERM, KEYWORD_TERM, IDENTIFIER_TERM, ARRAY_TERM, CALL_TERM,
        PARENTHESIS_TERM, UNARY_TERM, EXPRESSION, EXPRESSION_LIST, IF, LET, DO,
        WHILE, RETURN, STATEMENTS, VAR_DEC, PARAMETER_LIST, SUBROUTINE_BODY,
        SUBROUTINE_DEC, CLASS_VAR_DEC, CLASS
    };
}

#endif
